import type {
  Department,
  GrievanceCategory,
  GovernmentAuthority,
  School,
  Grievance,
  GrievanceTemplate,
  PublicDashboardStats,
  BottleneckAnalytics,
  User,
} from "../types/samarthya";

export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: "dept-phed",
    departmentCode: "PHED",
    departmentName: "Public Health Engineering / Jal Board",
    description: "Drinking water pipeline, submersible pumps, overhead water tanks, tap sanitation",
  },
  {
    id: "dept-pwd",
    departmentCode: "PWD",
    departmentName: "Public Works Department",
    description: "Classroom civil structures, boundary walls, roof leakages, toilet construction",
  },
  {
    id: "dept-doe",
    departmentCode: "DOE",
    departmentName: "Directorate of Education",
    description: "Teachers appointment, textbooks, Mid-Day Meals, classroom furniture, academics",
  },
  {
    id: "dept-mcd",
    departmentCode: "MCD",
    departmentName: "Municipal Corporation Education Wing",
    description: "Primary school campus sanitation, solid waste disposal, vector control",
  },
  {
    id: "dept-elec",
    departmentCode: "DISCOM",
    departmentName: "State Electricity Board / Power Utility",
    description: "School power connections, classroom ceiling fans, wiring safety, meter issues",
  },
];

export const MOCK_CATEGORIES: GrievanceCategory[] = [
  {
    id: "cat-water",
    categoryCode: "WATER_SANITATION",
    categoryName: "पेयजल एवं स्वच्छता (Water & Sanitation)",
    defaultSlaDays: 10,
    defaultPriority: "HIGH",
    iconUrl: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=100&auto=format&fit=crop&q=60",
    description: "Drinking water taps, storage tanks, submersible pump faults, contaminated water supply",
    department: MOCK_DEPARTMENTS[0],
  },
  {
    id: "cat-toilet",
    categoryCode: "TOILET_REPAIR",
    categoryName: "बालक एवं बालिका शौचालय (Toilet Facilities)",
    defaultSlaDays: 7,
    defaultPriority: "CRITICAL",
    iconUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=100&auto=format&fit=crop&q=60",
    description: "Non-functional girls/boys toilets, broken doors, choked drainage, lack of running water",
    department: MOCK_DEPARTMENTS[1],
  },
  {
    id: "cat-building",
    categoryCode: "BUILDING_INFRA",
    categoryName: "भवन एवं चारदीवारी मरम्मत (Building & Boundary)",
    defaultSlaDays: 20,
    defaultPriority: "HIGH",
    iconUrl: "https://images.unsplash.com/photo-1590402494587-44b71d7772f6?w=100&auto=format&fit=crop&q=60",
    description: "Cracked ceiling plaster, broken boundary wall allowing stray cattle, roof seepage during monsoon",
    department: MOCK_DEPARTMENTS[1],
  },
  {
    id: "cat-mdm",
    categoryCode: "MID_DAY_MEAL",
    categoryName: "मध्याह्न भोजन गुणवत्ता (Mid-Day Meal)",
    defaultSlaDays: 5,
    defaultPriority: "CRITICAL",
    iconUrl: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=100&auto=format&fit=crop&q=60",
    description: "Substandard grain quality, unhygienic kitchen shed, irregularity in daily meal distribution",
    department: MOCK_DEPARTMENTS[2],
  },
  {
    id: "cat-electricity",
    categoryCode: "ELECTRICITY_POWER",
    categoryName: "विद्युत आपूर्ति व पंखे (Electricity & Fans)",
    defaultSlaDays: 12,
    defaultPriority: "MEDIUM",
    iconUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=100&auto=format&fit=crop&q=60",
    description: "Burnt electrical wiring, non-functional classroom ceiling fans in summer, voltage fluctuation",
    department: MOCK_DEPARTMENTS[4],
  },
  {
    id: "cat-teachers",
    categoryCode: "TEACHER_VACANCY",
    categoryName: "शिक्षकों की कमी (Subject Teacher Shortage)",
    defaultSlaDays: 30,
    defaultPriority: "HIGH",
    iconUrl: "https://images.unsplash.com/photo-1577896851231-70ef18881754?w=100&auto=format&fit=crop&q=60",
    description: "No dedicated Mathematics/Science teacher for Class 9th & 10th for more than 6 months",
    department: MOCK_DEPARTMENTS[2],
  },
];

export const MOCK_AUTHORITIES: GovernmentAuthority[] = [
  {
    id: "auth-sonipat-phed",
    designation: "Executive Engineer (PHED)",
    officeName: "Office of the Executive Engineer, PHED Sonipat",
    officerName: "Er. Anil Verma",
    jurisdictionLevel: "DISTRICT",
    jurisdictionState: "Haryana",
    jurisdictionDistrict: "Sonipat",
    jurisdictionBlock: "Sonipat Rural",
    officialEmail: "ee.phed.sonipat@haryana.gov.in",
    officialPhone: "+91 130 2223344",
    officeAddress: "Civil Lines, Near Mini Secretariat, Sonipat, Haryana 131001",
    pincode: "131001",
    department: MOCK_DEPARTMENTS[0],
  },
  {
    id: "auth-delhi-pwd",
    designation: "Superintending Engineer (PWD)",
    officeName: "Office of SE, PWD North-East Education Division",
    officerName: "Er. Rajesh Saxena",
    jurisdictionLevel: "DISTRICT",
    jurisdictionState: "Delhi",
    jurisdictionDistrict: "North East Delhi",
    jurisdictionBlock: "Yamuna Vihar",
    officialEmail: "se.pwd.ne@delhi.gov.in",
    officialPhone: "+91 11 22819922",
    officeAddress: "PWD Office Complex, Opp. Gokalpuri Metro, Delhi 110094",
    pincode: "110094",
    department: MOCK_DEPARTMENTS[1],
  },
  {
    id: "auth-delhi-dde",
    designation: "Deputy Director of Education (DDE)",
    officeName: "Directorate of Education, Zone 4 North East Delhi",
    officerName: "Dr. Sunita Grover",
    jurisdictionLevel: "DISTRICT",
    jurisdictionState: "Delhi",
    jurisdictionDistrict: "North East Delhi",
    jurisdictionBlock: "Seelampur",
    officialEmail: "dde.northeast@delhi.gov.in",
    officialPhone: "+91 11 22812345",
    officeAddress: "Directorate of Education, Zone 4, Yamuna Vihar, Delhi 110053",
    pincode: "110053",
    department: MOCK_DEPARTMENTS[2],
  },
  {
    id: "auth-patiala-beo",
    designation: "Block Education Officer (BEO)",
    officeName: "Block Primary Education Office, Nabha",
    officerName: "Sardar Manjit Singh",
    jurisdictionLevel: "BLOCK",
    jurisdictionState: "Punjab",
    jurisdictionDistrict: "Patiala",
    jurisdictionBlock: "Nabha",
    officialEmail: "beo.nabha@punjab.gov.in",
    officialPhone: "+91 1765 220194",
    officeAddress: "Tehsil Complex, Circular Road, Nabha, Punjab 147201",
    pincode: "147201",
    department: MOCK_DEPARTMENTS[2],
  },
];

export const MOCK_SCHOOLS: School[] = [
  {
    id: "sch-sonipat-01",
    udiseCode: "06080100101",
    schoolName: "Govt Boys Senior Secondary School, Sonipat",
    state: "Haryana",
    district: "Sonipat",
    block: "Sonipat Rural",
    villageOrWard: "Murthal Road",
    pincode: "131001",
    latitude: 29.023841,
    longitude: 77.071239,
    category: "Senior Secondary (1-12)",
    managementType: "Department of Education",
    totalStudentsEnrolled: 480,
    headmasterName: "Sh. Rajesh Sharma",
    headmasterPhone: "+91 98123 45678",
    totalGrievancesCount: 8,
    resolvedGrievancesCount: 5,
    hangedGrievancesCount: 1,
    distanceKm: 1.2,
  },
  {
    id: "sch-delhi-02",
    udiseCode: "07010100202",
    schoolName: "Govt Sarvodaya Kanya Vidyalaya, Seelampur",
    state: "Delhi",
    district: "North East Delhi",
    block: "Seelampur",
    villageOrWard: "Block A, Seelampur",
    pincode: "110053",
    latitude: 28.669812,
    longitude: 77.268914,
    category: "Secondary (6-10)",
    managementType: "Govt of NCT of Delhi",
    totalStudentsEnrolled: 740,
    headmasterName: "Smt. Sunita Rani",
    headmasterPhone: "+91 98112 23344",
    totalGrievancesCount: 6,
    resolvedGrievancesCount: 4,
    hangedGrievancesCount: 2,
    distanceKm: 3.4,
  },
  {
    id: "sch-nabha-03",
    udiseCode: "03020100303",
    schoolName: "Govt High School, Nabha",
    state: "Punjab",
    district: "Patiala",
    block: "Nabha",
    villageOrWard: "Bhadson Road",
    pincode: "147201",
    latitude: 30.37521,
    longitude: 76.15289,
    category: "High School (6-10)",
    managementType: "Punjab School Education Board",
    totalStudentsEnrolled: 320,
    headmasterName: "S. Gurmeet Singh",
    headmasterPhone: "+91 98765 12345",
    totalGrievancesCount: 4,
    resolvedGrievancesCount: 3,
    hangedGrievancesCount: 0,
    distanceKm: 5.1,
  },
  {
    id: "sch-gurgaon-04",
    udiseCode: "06180100404",
    schoolName: "Govt Model Sanskriti Primary School, Badshahpur",
    state: "Haryana",
    district: "Gurugram",
    block: "Sohna",
    villageOrWard: "Badshahpur Main",
    pincode: "122101",
    latitude: 28.36382,
    longitude: 77.05432,
    category: "Primary (1-5)",
    managementType: "Department of Education",
    totalStudentsEnrolled: 290,
    headmasterName: "Smt. Kavita Yadav",
    headmasterPhone: "+91 99912 34567",
    totalGrievancesCount: 5,
    resolvedGrievancesCount: 2,
    hangedGrievancesCount: 1,
    distanceKm: 8.7,
  },
  {
    id: "sch-delhi-05",
    udiseCode: "07010100505",
    schoolName: "Govt Co-Ed Senior Secondary School, Yamuna Vihar",
    state: "Delhi",
    district: "North East Delhi",
    block: "Yamuna Vihar",
    villageOrWard: "C-Block Yamuna Vihar",
    pincode: "110053",
    latitude: 28.694812,
    longitude: 77.278914,
    category: "Senior Secondary (6-12)",
    managementType: "Govt of NCT of Delhi",
    totalStudentsEnrolled: 980,
    headmasterName: "Dr. Ashok Mathur",
    headmasterPhone: "+91 98100 44321",
    totalGrievancesCount: 11,
    resolvedGrievancesCount: 7,
    hangedGrievancesCount: 3,
    distanceKm: 2.8,
  },
];

export const MOCK_TEMPLATES: GrievanceTemplate[] = [
  {
    templateId: "tpl-water-hi",
    categoryId: "cat-water",
    language: "hi",
    templateTitle: "पेयजल एवं स्वच्छता सुविधा मरम्मत प्रार्थना पत्र",
    subjectTemplate:
      "विषय: {school_name} (UDISE: {udise_code}) में {facility_affected} की तत्काल मरम्मत एवं कार्यशीलता सुनिश्चित करने हेतु।",
    bodyMarkdownTemplate: `सेवा में,
श्रीमान अधिशासी अभियंता महोदय,
{authority_office_name},
{authority_address}

महोदय,

सविनय निवेदन है कि हम विद्यालय प्रबंधन समिति (SMC) के सदस्य आपका ध्यान विद्यालय की एक अत्यंत गंभीर समस्या की ओर आकर्षित करना चाहते हैं।

विद्यालय विवरण:
- विद्यालय: **{school_name}**
- UDISE कोड: **{udise_code}**
- ग्राम/वार्ड: **{village}**, ब्लॉक: **{block}**, जिला: **{district}**

समस्या का विवरण:
- प्रभावित सुविधा: **{facility_affected}**
- समस्या की प्रकृति: **{specific_problem}**
- समस्या की अवधि: **{duration_of_issue}**

उल्लेखनीय है कि निःशुल्क और अनिवार्य बाल शिक्षा का अधिकार अधिनियम (RTE Act, 2009) की धारा 19 एवं अनुसूची के अनुसार प्रत्येक विद्यालय में स्वच्छ पेयजल एवं क्रियाशील प्रसाधन सुविधा प्रदान करना राज्य का संवैधानिक उत्तरदायित्व है।

अतः आपसे करबद्ध निवेदन है कि जनहित एवं बालिकाओं के स्वास्थ्य को ध्यान में रखते हुए इस प्रार्थना पत्र पर त्वरित संज्ञान लेते हुए संबंधित तकनीकी शाखा को निरीक्षण एवं मरम्मत का आदेश जारी करने की कृपा करें।

भवदीय / भवदीया,
विद्यालय प्रबंधन समिति (SMC)
{school_name}`,
    requiredVariables: [
      {
        key: "facility_affected",
        label: "प्रभावित सुविधा (जैसे: पीने के पानी की टंकी व नल)",
        type: "string",
        required: true,
        placeholder: "उदा. पीने के पानी की टंकी",
      },
      {
        key: "specific_problem",
        label: "समस्या क्या है?",
        type: "string",
        required: true,
        placeholder: "उदा. टंकी टूटी है और नलों में पानी नहीं आ रहा",
      },
      {
        key: "duration_of_issue",
        label: "समस्या कितने समय से है?",
        type: "string",
        required: true,
        placeholder: "उदा. 2 महीने से",
      },
    ],
    legalReferences: "Section 19 & Schedule of RTE Act 2009",
  },
  {
    templateId: "tpl-toilet-hi",
    categoryId: "cat-toilet",
    language: "hi",
    templateTitle: "बालिका एवं बालक शौचालय मरम्मत प्रार्थना पत्र",
    subjectTemplate:
      "विषय: {school_name} (UDISE: {udise_code}) में {facility_affected} की मरम्मत एवं स्वच्छता व्यवस्था हेतु।",
    bodyMarkdownTemplate: `सेवा में,
कार्यपालक अभियंता महोदय (PWD),
{authority_office_name},
{authority_address}

महोदय,

विद्यालय **{school_name}** (UDISE: **{udise_code}**) में {facility_affected} की स्थिति अत्यधिक दयनीय है।

समस्या विवरण:
- समस्या: **{specific_problem}**
- अवधि: **{duration_of_issue}**

RTE Act 2009 के मानदण्डों के तहत तुरंत कार्रवाई कर मरम्मत कराई जाए।

भवदीय,
SMC समिति, {school_name}`,
    requiredVariables: [
      {
        key: "facility_affected",
        label: "प्रभावित सुविधा (जैसे: बालिका शौचालय)",
        type: "string",
        required: true,
      },
      {
        key: "specific_problem",
        label: "समस्या का विवरण",
        type: "string",
        required: true,
      },
      {
        key: "duration_of_issue",
        label: "समस्या की अवधि",
        type: "string",
        required: true,
      },
    ],
    legalReferences: "RTE Act 2009 Norms for Separate Sanitation",
  },
];

export const MOCK_GRIEVANCES: Grievance[] = [
  {
    id: "grievance-01",
    ticketNumber: "SAM-202609-0842",
    schoolId: "sch-sonipat-01",
    school: {
      id: "sch-sonipat-01",
      name: "Govt Boys Senior Secondary School, Sonipat",
      udise: "06080100101",
      district: "Sonipat",
      block: "Sonipat Rural",
    },
    categoryId: "cat-water",
    category: {
      id: "cat-water",
      code: "WATER_SANITATION",
      name: "पेयजल एवं स्वच्छता",
    },
    templateId: "tpl-water-hi",
    subject: "विषय: Govt Boys Senior Secondary School, Sonipat में पीने की पानी की टंकी की तत्काल मरम्मत हेतु।",
    formalLetterContent: `सेवा में,
श्रीमान अधिशासी अभियंता महोदय,
Office of the Executive Engineer, PHED Sonipat

महोदय,
विद्यालय में बालकों के लिए पीने के पानी की 1000 लीटर की टंकी 2 महीने से टूटी पड़ी है। नलों में पानी न आने से छात्र-छात्राओं को बाहर से पानी लाना पड़ रहा है।
कृपया तत्काल संज्ञान लें।

भवदीय,
SMC समिति`,
    letterPdfUrl: "https://storage.samarthya.org/letters/SAM-202609-0842.pdf",
    assignedAuthority: {
      id: "auth-sonipat-phed",
      designation: "Executive Engineer (PHED)",
      officeName: "Office of the Executive Engineer, PHED Sonipat",
      officerName: "Er. Anil Verma",
      officialEmail: "ee.phed.sonipat@haryana.gov.in",
      officialPhone: "+91 130 2223344",
      officeAddress: "Civil Lines, Near Mini Secretariat, Sonipat, Haryana 131001",
    },
    status: "IN_PROGRESS",
    priority: "HIGH",
    submissionChannel: "HYBRID",
    sla: {
      slaDays: 10,
      deadline: "2026-09-28T18:00:00.000Z",
      isHanged: false,
      isBreached: false,
      daysRemaining: 7,
      escalationLevel: 1,
    },
    dynamicFieldValues: {
      facility_affected: "पीने के पानी की टंकी",
      specific_problem: "टंकी टूटी है और नलों में पानी नहीं आ रहा",
      duration_of_issue: "2 महीने",
    },
    attachments: [
      {
        id: "att-1",
        fileUrl: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=800&auto=format&fit=crop&q=60",
        attachmentType: "ISSUE_PHOTO",
        caption: "Damaged PVC pipeline joint & tank top",
      },
    ],
    timeline: [
      {
        id: "evt-1",
        eventType: "CREATED",
        performedBy: "Ramesh Kumar (SMC Member)",
        timestamp: "2026-09-18T10:00:00.000Z",
        comment: "Grievance submitted by SMC Member through Audio Recording pipeline",
      },
      {
        id: "evt-2",
        eventType: "DISPATCHED_DIGITALLY",
        performedBy: "Samarthya System Dispatcher",
        timestamp: "2026-09-18T10:01:00.000Z",
        comment: "Official grievance email & SMS alert dispatched with action link to EE PHED Sonipat",
      },
      {
        id: "evt-3",
        eventType: "ACKNOWLEDGED_BY_OFFICER",
        performedBy: "Er. Anil Verma (Authority)",
        timestamp: "2026-09-19T11:30:00.000Z",
        comment: "Inspection team scheduled for site survey by Junior Engineer Vikas",
      },
    ],
    upvotesCount: 142,
    hasUserUpvoted: false,
    actionToken: "4e82b7190f84a761e0b1c938d827a6f203847b2c9e78291f0482b61928374a5e",
    createdAt: "2026-09-18T10:00:00.000Z",
  },
  {
    id: "grievance-02",
    ticketNumber: "SAM-202609-0202",
    schoolId: "sch-delhi-02",
    school: {
      id: "sch-delhi-02",
      name: "Govt Sarvodaya Kanya Vidyalaya, Seelampur",
      udise: "07010100202",
      district: "North East Delhi",
      block: "Seelampur",
    },
    categoryId: "cat-toilet",
    category: {
      id: "cat-toilet",
      code: "TOILET_REPAIR",
      name: "बालक एवं बालिका शौचालय",
    },
    templateId: "tpl-toilet-hi",
    subject: "विषय: Govt Sarvodaya Kanya Vidyalaya में बालिका शौचालय के चोक फ्लश व दरवाजे टूटने बाबत।",
    formalLetterContent: `सेवा में,\nअधीक्षण अभियंता महोदय, PWD\n\nबालिका शौचालय के 6 में से 5 केबिन के दरवाजे टूटे हैं जिससे 740 छात्राओं को अत्यधिक असुविधा हो रही है।`,
    letterPdfUrl: "https://storage.samarthya.org/letters/SAM-202609-0202.pdf",
    assignedAuthority: {
      id: "auth-delhi-pwd",
      designation: "Superintending Engineer (PWD)",
      officeName: "Office of SE, PWD North-East Division",
      officerName: "Er. Rajesh Saxena",
      officialEmail: "se.pwd.ne@delhi.gov.in",
      officialPhone: "+91 11 22819922",
    },
    status: "UNDER_INSPECTION",
    priority: "CRITICAL",
    submissionChannel: "HYBRID",
    sla: {
      slaDays: 7,
      deadline: "2026-09-22T18:00:00.000Z",
      isHanged: false,
      isBreached: false,
      daysRemaining: 3,
      escalationLevel: 1,
    },
    dynamicFieldValues: {
      facility_affected: "बालिका शौचालय",
      specific_problem: "दरवाजे टूटे हैं और पानी नहीं आ रहा",
      duration_of_issue: "1 माह",
    },
    attachments: [
      {
        id: "att-2",
        fileUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=60",
        attachmentType: "ISSUE_PHOTO",
        caption: "Broken toilet cubicle doors",
      },
    ],
    timeline: [
      {
        id: "evt-201",
        eventType: "CREATED",
        performedBy: "Sunita Rani (Headmaster)",
        timestamp: "2026-09-15T09:15:00.000Z",
        comment: "Emergency grievance submitted by School Chairperson",
      },
      {
        id: "evt-202",
        eventType: "ACKNOWLEDGED_BY_OFFICER",
        performedBy: "PWD North East Office",
        timestamp: "2026-09-16T14:00:00.000Z",
        comment: "Work order WO-2026-PWD-892 issued for door replacement",
      },
    ],
    upvotesCount: 312,
    hasUserUpvoted: true,
    actionToken: "39756e48bf6ea757335f70960bc45a87e785d42e1eda898bc032c2aa58ed253f",
    createdAt: "2026-09-15T09:15:00.000Z",
  },
  {
    id: "grievance-03",
    ticketNumber: "SAM-202608-0101",
    schoolId: "sch-sonipat-01",
    school: {
      id: "sch-sonipat-01",
      name: "Govt Boys Senior Secondary School, Sonipat",
      udise: "06080100101",
      district: "Sonipat",
      block: "Sonipat Rural",
    },
    categoryId: "cat-building",
    category: {
      id: "cat-building",
      code: "BUILDING_INFRA",
      name: "भवन एवं चारदीवारी मरम्मत",
    },
    subject: "विषय: स्कूल के पीछे की 40 फीट चारदीवारी गिरने से आवारा पशुओं के घुसने बाबत।",
    formalLetterContent: `सेवा में,\nPWD कार्यपालक अभियंता,\n\nभारी वर्षा के कारण स्कूल की 40 फीट दीवार गिर गई है। 480 छात्रों की सुरक्षा खतरे में है।`,
    assignedAuthority: {
      id: "auth-sonipat-phed",
      designation: "Executive Engineer (PWD)",
      officeName: "Office of EE PWD Sonipat",
      officerName: "Er. S.K. Bansal",
      officialEmail: "ee.pwd.sonipat@haryana.gov.in",
      officialPhone: "+91 130 2229988",
    },
    status: "HANGED",
    priority: "HIGH",
    submissionChannel: "DIGITAL_DISPATCH",
    sla: {
      slaDays: 20,
      deadline: "2026-08-30T18:00:00.000Z",
      isHanged: true,
      isBreached: true,
      daysRemaining: 0,
      escalationLevel: 2,
    },
    attachments: [
      {
        id: "att-3",
        fileUrl: "https://images.unsplash.com/photo-1590402494587-44b71d7772f6?w=800&auto=format&fit=crop&q=60",
        attachmentType: "ISSUE_PHOTO",
        caption: "Collapsed brick wall rear ground",
      },
    ],
    timeline: [
      {
        id: "evt-301",
        eventType: "CREATED",
        performedBy: "Ramesh Kumar (SMC Member)",
        timestamp: "2026-08-10T11:00:00.000Z",
        comment: "Grievance submitted",
      },
      {
        id: "evt-302",
        eventType: "MANUALLY_ESCALATED",
        performedBy: "Samarthya Admin",
        timestamp: "2026-09-05T16:00:00.000Z",
        comment: "SLA breached by 15 days. Escalated to District Magistrate Sonipat.",
      },
    ],
    upvotesCount: 489,
    hasUserUpvoted: false,
    actionToken: "7c981ab20938472910fa892b1c82736450192837465019283746501928374650",
    createdAt: "2026-08-10T11:00:00.000Z",
  },
  {
    id: "grievance-04",
    ticketNumber: "SAM-202607-0050",
    schoolId: "sch-nabha-03",
    school: {
      id: "sch-nabha-03",
      name: "Govt High School, Nabha",
      udise: "03020100303",
      district: "Patiala",
      block: "Nabha",
    },
    categoryId: "cat-electricity",
    category: {
      id: "cat-electricity",
      code: "ELECTRICITY_POWER",
      name: "विद्युत आपूर्ति व पंखे",
    },
    subject: "विषय: 6 कक्षाओं में पंखे जलने व बिजली तार टूटने की समस्या का निवारण।",
    assignedAuthority: {
      id: "auth-patiala-beo",
      designation: "Block Education Officer",
      officeName: "Office of BEO Nabha",
      officerName: "Sardar Manjit Singh",
      officialEmail: "beo.nabha@punjab.gov.in",
      officialPhone: "+91 1765 220194",
    },
    status: "RESOLVED",
    priority: "MEDIUM",
    submissionChannel: "PHYSICAL_RECEIPT",
    sla: {
      slaDays: 12,
      deadline: "2026-07-25T18:00:00.000Z",
      isHanged: false,
      isBreached: false,
      daysRemaining: 0,
      escalationLevel: 1,
    },
    attachments: [
      {
        id: "att-4",
        fileUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=60",
        attachmentType: "RESOLUTION_PROOF",
        caption: "Repaired wiring and newly mounted Usha ceiling fans",
      },
    ],
    timeline: [
      {
        id: "evt-401",
        eventType: "CREATED",
        performedBy: "S. Gurmeet Singh",
        timestamp: "2026-07-12T10:00:00.000Z",
        comment: "Physical receipt submitted at BEO office",
      },
      {
        id: "evt-402",
        eventType: "RESOLVED_BY_OFFICER",
        performedBy: "PSPCL Electrical Team",
        timestamp: "2026-07-20T15:30:00.000Z",
        comment: "New fans installed and transformer line stabilized",
      },
      {
        id: "evt-403",
        eventType: "VERIFIED_BY_SMC",
        performedBy: "SMC Committee Nabha",
        timestamp: "2026-07-22T09:00:00.000Z",
        comment: "Ground verification completed. Working properly.",
      },
    ],
    upvotesCount: 88,
    hasUserUpvoted: false,
    actionToken: "1928374650192837465019283746501928374650192837465019283746501928",
    createdAt: "2026-07-12T10:00:00.000Z",
  },
];

export const MOCK_USERS: Record<string, User> = {
  SMC_MEMBER: {
    id: "user-smc-01",
    phoneNumber: "+91 98765 43210",
    fullName: "Ramesh Kumar",
    email: "ramesh.kumar@smc.samarthya.org",
    role: "SMC_MEMBER",
    preferredLanguage: "hi",
    isPhoneVerified: true,
    avatarUrl: "/images/user/owner.png",
    associatedSchools: [
      {
        schoolId: "sch-sonipat-01",
        schoolName: "Govt Boys Senior Secondary School, Sonipat",
        udiseCode: "06080100101",
        designation: "PARENT_MEMBER",
      },
    ],
  },
  CITIZEN: {
    id: "user-citizen-01",
    phoneNumber: "+91 98123 99999",
    fullName: "Pooja Verma",
    email: "pooja.verma@gmail.com",
    role: "CITIZEN",
    preferredLanguage: "hi",
    isPhoneVerified: true,
    avatarUrl: "/images/user/user-02.png",
  },
  GOVERNMENT_OFFICER: {
    id: "user-officer-01",
    phoneNumber: "+91 130 2223344",
    fullName: "Er. Anil Verma",
    email: "ee.phed.sonipat@haryana.gov.in",
    role: "GOVERNMENT_OFFICER",
    preferredLanguage: "en",
    isPhoneVerified: true,
    avatarUrl: "/images/user/user-03.png",
  },
  SAMARTHYA_ADMIN: {
    id: "user-admin-01",
    phoneNumber: "+91 99999 88888",
    fullName: "Priya Sundaram",
    email: "admin@samarthya.org",
    role: "SAMARTHYA_ADMIN",
    preferredLanguage: "en",
    isPhoneVerified: true,
    avatarUrl: "/images/user/user-01.png",
  },
};

export const MOCK_PUBLIC_STATS: PublicDashboardStats = {
  totalSchoolsEmpowered: 19420,
  totalGrievancesFiled: 14850,
  totalResolved: 11980,
  totalHanged: 1420,
  resolutionRatePercentage: 80.7,
  averageResolutionDays: 14.2,
  categoryBreakdown: [
    {
      category: "पेयजल एवं स्वच्छता",
      categoryCode: "WATER_SANITATION",
      total: 5120,
      resolved: 4210,
      hanged: 490,
    },
    {
      category: "शौचालय मरम्मत",
      categoryCode: "TOILET_REPAIR",
      total: 3840,
      resolved: 3100,
      hanged: 430,
    },
    {
      category: "भवन एवं चारदीवारी",
      categoryCode: "BUILDING_INFRA",
      total: 2980,
      resolved: 2150,
      hanged: 310,
    },
    {
      category: "मध्याह्न भोजन गुणवत्ता",
      categoryCode: "MID_DAY_MEAL",
      total: 1540,
      resolved: 1390,
      hanged: 70,
    },
    {
      category: "विद्युत आपूर्ति व पंखे",
      categoryCode: "ELECTRICITY_POWER",
      total: 1370,
      resolved: 1130,
      hanged: 120,
    },
  ],
  topPerformingDistricts: [
    { district: "North East Delhi", resolutionRate: 88.4 },
    { district: "Sonipat", resolutionRate: 85.1 },
    { district: "Patiala", resolutionRate: 83.9 },
    { district: "Gurugram", resolutionRate: 79.2 },
    { district: "Ludhiana", resolutionRate: 76.5 },
  ],
};

export const MOCK_BOTTLENECK_ANALYTICS: BottleneckAnalytics = {
  worstPerformingDepartments: [
    {
      departmentCode: "PWD",
      departmentName: "Public Works Department",
      openGrievances: 412,
      hangedGrievances: 184,
      averageDaysToResolve: 48,
    },
    {
      departmentCode: "PHED",
      departmentName: "Public Health Engineering / Jal Board",
      openGrievances: 289,
      hangedGrievances: 96,
      averageDaysToResolve: 32,
    },
    {
      departmentCode: "DOE",
      departmentName: "Directorate of Education",
      openGrievances: 145,
      hangedGrievances: 38,
      averageDaysToResolve: 21,
    },
    {
      departmentCode: "DISCOM",
      departmentName: "State Power Utility",
      openGrievances: 88,
      hangedGrievances: 19,
      averageDaysToResolve: 16,
    },
  ],
  worstPerformingDistricts: [
    {
      district: "North East Delhi",
      openGrievances: 342,
      hangedGrievances: 112,
      escalationRatePercentage: 32.7,
    },
    {
      district: "Sonipat",
      openGrievances: 210,
      hangedGrievances: 74,
      escalationRatePercentage: 28.5,
    },
    {
      district: "Patiala",
      openGrievances: 145,
      hangedGrievances: 42,
      escalationRatePercentage: 21.0,
    },
    {
      district: "Gurugram",
      openGrievances: 118,
      hangedGrievances: 31,
      escalationRatePercentage: 18.2,
    },
  ],
};
