export const DB_NAME = "samarthya_core_db";

export const USER_ROLES = {
  SMC_MEMBER: "SMC_MEMBER",
  SAMARTHYA_ADMIN: "SAMARTHYA_ADMIN",
  SAMARTHYA_COORDINATOR: "SAMARTHYA_COORDINATOR",
  GOVERNMENT_OFFICER: "GOVERNMENT_OFFICER",
  CITIZEN: "CITIZEN",
};

export const SUPPORTED_LANGUAGES = {
  HINDI: "hi",
  PUNJABI: "pa",
  ENGLISH: "en",
};

export const GRIEVANCE_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  ACKNOWLEDGED: "ACKNOWLEDGED",
  UNDER_INSPECTION: "UNDER_INSPECTION",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
  HANGED: "HANGED",
};

export const PRIORITY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

export const SUBMISSION_CHANNELS = {
  DIGITAL_DISPATCH: "DIGITAL_DISPATCH",
  PHYSICAL_MANUAL: "PHYSICAL_MANUAL",
  HYBRID: "HYBRID",
};
